

INSERT INTO lift (type, bodyPart, name, sets, reps, link ) VALUES
('weight', 'chest', 'Bench Press', 5, 6, 'https://www.youtube.com/watch?v=4T9UQ4FBVXI'),
('weight', 'chest', 'Incline Bench Press', 5, 6, 'https://www.youtube.com/watch?v=QeXECbti2gU'),
('weight', 'chest', 'Decline Bench Press', 5, 6, 'https://www.youtube.com/watch?v=OR6WM5Z2Hqs'),
('weight', 'chest', 'Dumb Bell Fly', 5, 6, 'https://www.youtube.com/watch?v=eozdVDA78K0'),
('weight', 'chest', 'Incline Dumb Bell Fly', 5, 6, 'https://www.youtube.com/watch?v=bDaIL_zKbGs'),
('weight', 'chest', 'Dumb Bell Press', 5, 6, 'https://www.youtube.com/watch?v=VmB1G1K7v94'),
('weight', 'chest', 'Reverse Grip Bench Press', 5, 6, 'https://www.youtube.com/watch?v=E5dK-30ychY'),
('weight', 'chest', 'Pec Deck', 5, 6, 'https://www.youtube.com/watch?v=WMte8QiV9h8'),
('weight', 'chest', 'Cable Cross Over', 5, 6, 'https://www.youtube.com/watch?v=Iwe6AmxVf7o'),
('weight', 'chest', 'Incline Chest Press (Machine)', 5, 6, 'https://www.youtube.com/watch?v=ig0NyNlSce4'),
('weight', 'chest', 'Tricep Pushdown', 5, 6, 'https://www.youtube.com/watch?v=2-LAMcpzODU'),
('weight', 'chest', 'Skull Crusher', 5, 6, 'https://www.youtube.com/watch?v=d_KZxkY_0cM'),
('weight', 'chest', 'Tricep Extension', 5, 6, 'https://www.youtube.com/watch?v=YbX7Wd8jQ-Q'),

('weight', 'legs', 'Lower Back Bar Squat', 5, 6, 'https://www.youtube.com/watch?v=QhVC_AnZYYM'),
('weight', 'legs', 'Bar Bell Lunges', 5, 6, 'https://www.youtube.com/watch?v=e5nVPlQcNCE'),
('weight', 'legs', 'Leg Press', 5, 6, 'https://www.youtube.com/watch?v=CHPHn-OnTqE'),
('weight', 'legs', 'Leg Extension', 5, 6, 'https://www.youtube.com/watch?v=YyvSfVjQeL0'),
('weight', 'legs', 'Lying Leg Curl', 5, 6, 'https://www.youtube.com/watch?v=1Tq3QdYUuHs'),
('weight', 'legs', 'Standing Calf Raise', 5, 6, 'https://www.youtube.com/watch?v=YMmgqO8Jo-k'),
('weight', 'legs', 'Front Squats', 5, 6, 'https://www.youtube.com/watch?v=VfBOBhwXbro'),
('weight', 'legs', 'Bulgarian Split Squats', 5, 6, 'https://www.youtube.com/watch?v=2C-uNgKwPLE'),

('weight', 'back', 'Bar Bell Row', 5, 6, 'https://www.youtube.com/watch?v=I0uhDZ06hrQ'),
('weight', 'back', 'Good Mornings', 5, 6, 'https://www.youtube.com/watch?v=5Xj6XUa77qc'),
('weight', 'back', 'Straight Legged Deadlift', 5, 6, 'https://www.youtube.com/watch?v=AH7gaaT_tU8'),
('weight', 'back', 'Dumb Bell Row', 5, 6, 'https://www.youtube.com/watch?v=pYcpY20QaE8'),
('weight', 'back', 'Latt Pull Down', 5, 6, 'https://www.youtube.com/watch?v=X5n55mMqSUs'),
('weight', 'back', 'Close Latt Pull Down', 5, 6, 'https://www.youtube.com/watch?v=ytT9MBNFCbo'),
('weight', 'back', 'Reverse Grip Latt Pull Down', 5, 6, 'https://www.youtube.com/watch?v=apzFTbsm7HU'),
('weight', 'back', 'Hammer Curls', 5, 6, 'https://www.youtube.com/watch?v=zC3nLlEvin4'),
('weight', 'back', 'Dumb Bell Curls', 5, 6, 'https://www.youtube.com/watch?v=yTWO2th-RIY'),
('weight', 'back', 'Preacher Dumb Bell Curls', 5, 6, 'https://www.youtube.com/watch?v=vngli9UR6Hw'),
('weight', 'back', 'Preacher Curl Bar', 5, 6, 'https://www.youtube.com/watch?v=fIWP-FRFNU0'),
('weight', 'back', 'Cable Curls', 5, 6, 'https://www.youtube.com/watch?v=L9GwtjwAM8Y'),

('weight', 'delts', 'Overhead Press', 5, 6, 'https://www.youtube.com/watch?v=CnBmiBqp-AI'),
('weight', 'delts', 'Side Lateral Raises', 5, 6, 'https://www.youtube.com/watch?v=3VcKaXpzqRo'),
('weight', 'delts', 'Front Lateral Raises', 5, 6, 'https://www.youtube.com/watch?v=-t7fuZ0KhDA'),
('weight', 'delts', 'Farmer Walk', 5, 6, 'https://www.youtube.com/watch?v=rt17lmnaLSM'),
('weight', 'delts', 'Shrugs Bar Bell', 5, 6, 'https://www.youtube.com/watch?v=-0t_hCzUgvM'),
('weight', 'delts', 'Rack Pull', 5, 6, 'https://www.youtube.com/watch?v=6ssG3e4ifsY'),
('weight', 'delts', 'Dumb Bell Shrugs', 5, 6, 'https://www.youtube.com/watch?v=xDt6qbKgLkY'),
('weight', 'delts', 'Hex Bar Shrugs', 5, 6, 'https://www.youtube.com/watch?v=sNnhjJt6Wdk'),
('weight', 'delts', 'Dumb Bell Overhead Press', 5, 6, 'https://www.youtube.com/watch?v=qEwKCR5JCog'),


('calisthenics', 'chest', 'Push Up', 5, 10, 'https://www.youtube.com/watch?v=cSPSc59Lq5Q'),
('calisthenics', 'chest', 'Incline Push Up', 5, 10, 'https://www.youtube.com/watch?v=bXsbK9UPu3c'),
('calisthenics', 'chest', 'Decline Push Up', 5, 10, 'https://www.youtube.com/watch?v=SKPab2YC8BE'),
('calisthenics', 'chest', 'Dips', 5, 10, 'https://www.youtube.com/watch?v=jMbLfZly08U'),
('calisthenics', 'chest', 'Diamond Push Up', 5, 10, 'https://www.youtube.com/watch?v=J0DnG1_S92I'),
('calisthenics', 'chest', 'Tiger Push Up', 5, 10, 'https://www.youtube.com/watch?v=71XcAgEGQzY'),
('calisthenics', 'chest', 'Wide Grip Push Up', 5, 10, 'https://www.youtube.com/watch?v=rr6eFNNDQdU'),

('calisthenics', 'legs', 'Squats', 5, 10, 'https://www.youtube.com/watch?v=R1v152b72lo'),
('calisthenics', 'legs', 'Lunges', 5, 10, 'https://www.youtube.com/watch?v=QF0BQS2W80k'),
('calisthenics', 'legs', 'Calf Raises', 5, 10, 'https://www.youtube.com/watch?v=ommnfVcLWxQ'),
('calisthenics', 'legs', 'Wide Squat', 5, 10, 'https://www.youtube.com/watch?v=v2ukjHXbXVo'),
('calisthenics', 'legs', 'Drinking Bird', 5, 10, 'https://www.youtube.com/watch?v=SWTwMeAqJTY'),
('calisthenics', 'legs', 'Close Stance Squat', 5, 10, 'https://www.youtube.com/watch?v=f-Nd2SbGf1M'),
('calisthenics', 'legs', 'Single-leg Bridge', 5, 10, 'https://www.youtube.com/watch?v=Y-6Gonx2Wpo'),
('calisthenics', 'legs', 'Side Lunge', 5, 10, 'https://www.youtube.com/watch?v=FUX6Pz8vV0s'),
('calisthenics', 'legs', 'Cossack Squat', 5, 10, 'https://www.youtube.com/watch?v=tpczTeSkHz0'),
('calisthenics', 'legs', 'Reverse Lunge', 5, 10, 'https://www.youtube.com/watch?v=nwi_JkLOAyw'),

('calisthenics', 'back', 'Pull Up', 5, 10, 'https://www.youtube.com/watch?v=bAEua0zu_74'),
('calisthenics', 'back', 'Reverse Snow Angel', 5, 10, 'https://www.youtube.com/watch?v=Rwm7QgLllSA'),
('calisthenics', 'back', 'Back Hyperextension', 5, 10, 'https://www.youtube.com/watch?v=PPMh6lrG5mk'),
('calisthenics', 'back', 'Scapula Pushup', 5, 10, 'https://www.youtube.com/watch?v=5YHZnEsE9hA'),
('calisthenics', 'back', 'Inverted Rows', 5, 10, 'https://www.youtube.com/watch?v=LhGIbVryarw'),
('calisthenics', 'back', 'Pullup Iso Hold', 5, 10, 'https://www.youtube.com/watch?v=MzE0f1VEiUA'),
('calisthenics', 'back', 'Superman Plank', 5, 10, 'https://www.youtube.com/watch?v=BB1GMJ-WHqo'),

('calisthenics', 'delts', 'Handstand Push Up', 5, 10, 'https://www.youtube.com/watch?v=Rhgu1b6fD4E'),
('calisthenics', 'delts', 'Decline Pike Push Up', 5, 10, 'https://www.youtube.com/watch?v=XkR0zzZd6_E'),
('calisthenics', 'delts', 'YTWL', 5, 10, 'https://www.youtube.com/watch?v=tbvq18eKJ5Q'),
('calisthenics', 'delts', 'Pushup Planks', 5, 10, 'https://www.youtube.com/watch?v=dh34hajCVyk'),
('calisthenics', 'delts', 'Pull Ups', 5, 10, 'https://www.youtube.com/watch?v=bAEua0zu_74'),
('calisthenics', 'delts', 'Pullup Iso Hold', 5, 10, 'https://www.youtube.com/watch?v=MzE0f1VEiUA'),
