DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS lift;
DROP TABLE IF EXISTS routines;

CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  username VARCHAR(255) UNIQUE NOT NULL,
  password_digest TEXT NOT NULL,
);

CREATE TABLE IF NOT EXISTS lift (
  id SERIAL PRIMARY KEY,
  type VARCHAR(255),
  bodyPart VARCHAR(255),
  name VARCHAR(255),
  reps INTEGER,
  link VARCHAR(255),
)

CREATE TABLE IF NOT EXISTS routines (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(id),
  name VARCHAR(255),
  type VARCHAR(255),
  bodyPart VARCHAR(255),
  exercises1 INTEGER REFERENCES lift(id),
  exercises2 INTEGER REFERENCES lift(id),
  exercises3 INTEGER REFERENCES lift(id),
  exercises4 INTEGER REFERENCES lift(id),
)
